version: "3.8"
services:
  rserver:
    build:
      context: ./backend
      dockerfile: Dockerfile.r
    ports:
      - "8001:8001"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rserver
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend 